/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative */

#ifndef _Included_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
#define _Included_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeEnvEdgeInit
 * Signature: ([JJ[J[J[DLjava/util/ArrayList;I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeEnvEdgeInit
  (JNIEnv *, jobject, jlongArray, jlong, jlongArray, jlongArray, jdoubleArray, jobject, jint);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeStepMsgExecute
 * Signature: (J[J[Z[DIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeStepMsgExecute
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeStepVertexInput
 * Signature: (J[J[Z[DIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeStepVertexInput
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeStepGetMessages
 * Signature: (J[J[DIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeStepGetMessages
  (JNIEnv *, jobject, jlong, jlongArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeStepGetOldMessages
 * Signature: (J[J[Z[I[DIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeStepGetOldMessages
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jintArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeSkipVertexInput
 * Signature: (JIIIII)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeSkipVertexInput
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative
 * Method:    nativeEnvClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_GPUGraphX_algorithm_array_SSSP_GPUNative_nativeEnvClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
