/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch */

#ifndef _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
#define _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeEnvEdgeInit
 * Signature: ([JJ[J[J[DLjava/util/ArrayList;I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeEnvEdgeInit
  (JNIEnv *, jobject, jlongArray, jlong, jlongArray, jlongArray, jdoubleArray, jobject, jint);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeStepMsgInitInput
 * Signature: (J[J[Z[DIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeStepMsgInitInput
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeStepMsgBatchInput
 * Signature: (J[J[Z[DIIII)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeStepMsgBatchInput
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeStepMsgBatchExecute
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeStepMsgBatchExecute
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeStepFinal
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeStepFinal
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeSkipStep
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeSkipStep
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch
 * Method:    nativeEnvClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPBatch_GPUNativeBatch_nativeEnvClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
