/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative */

#ifndef _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
#define _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
 * Method:    nativeEnvEdgeInit
 * Signature: ([JJ[J[J[DLjava/util/ArrayList;I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative_nativeEnvEdgeInit
  (JNIEnv *, jobject, jlongArray, jlong, jlongArray, jlongArray, jdoubleArray, jobject, jint);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
 * Method:    nativeStepMsgExecute
 * Signature: (J[J[Z[DIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative_nativeStepMsgExecute
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
 * Method:    nativeSkipStep
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative_nativeSkipStep
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
 * Method:    nativeStepFinal
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative_nativeStepFinal
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative
 * Method:    nativeEnvClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSP_GPUNative_nativeEnvClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
