/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_PregelGPU_GPUNative */

#ifndef _Included_edu_ustc_nodb_PregelGPU_GPUNative
#define _Included_edu_ustc_nodb_PregelGPU_GPUNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_PregelGPU_GPUNative
 * Method:    GPUServerInit
 * Signature: ([JJ[J[J[DLjava/util/ArrayList;I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_GPUNative_GPUServerInit
        (JNIEnv *, jobject, jlongArray, jlong, jlongArray, jlongArray, jdoubleArray, jobject, jint);

/*
 * Class:     edu_ustc_nodb_PregelGPU_GPUNative
 * Method:    GPUClientAllSSSP
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_GPUNative_GPUClientAllStep
        (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_GPUNative
 * Method:    GPUClientSkippedSSSP
 * Signature: (JIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_GPUNative_GPUClientSkippedStep
        (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_GPUNative
 * Method:    GPUClientSSSP
 * Signature: (J[J[Z[DIIII[J[D)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_GPUNative_GPUClientStep
        (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint, jint, jlongArray, jdoubleArray);

/*
 * Class:     edu_ustc_nodb_PregelGPU_GPUNative
 * Method:    GPUServerShutdown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_GPUNative_GPUServerShutdown
        (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
