/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_SSSP_GPUNative */

#ifndef _Included_edu_ustc_nodb_SSSP_GPUNative
#define _Included_edu_ustc_nodb_SSSP_GPUNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_SSSP_GPUNative
 * Method:    GPUSSSP
 * Signature: (JLjava/util/ArrayList;Ljava/util/ArrayList;Ljava/util/ArrayList;)Ljava/util/ArrayList;
 */
JNIEXPORT jobject JNICALL Java_edu_ustc_nodb_SSSP_GPUNative_GPUSSSP
  (JNIEnv *, jobject, jlong, jobject, jobject, jobject);

#ifdef __cplusplus
}
#endif
#endif
