/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm */

#ifndef _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
#define _Included_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
 * Method:    nativeEnvEdgeInit
 * Signature: ([JJLjava/util/ArrayList;ILedu/ustc/nodb/PregelGPU/Algorithm/SSSPshm/shmManager/shmNamePackager/shmReaderPackager;)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm_nativeEnvEdgeInit
  (JNIEnv *, jobject, jlongArray, jlong, jobject, jint, jobject);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
 * Method:    nativeStepMsgExecute
 * Signature: (JLedu/ustc/nodb/PregelGPU/Algorithm/SSSPshm/shmManager/shmNamePackager/shmReaderPackager;Ledu/ustc/nodb/PregelGPU/Algorithm/SSSPshm/shmManager/shmNamePackager/shmWriterPackager;IIII)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm_nativeStepMsgExecute
  (JNIEnv *, jobject, jlong, jobject, jobject, jint, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
 * Method:    nativeSkipStep
 * Signature: (JIIIILedu/ustc/nodb/PregelGPU/Algorithm/SSSPshm/shmManager/shmNamePackager/shmWriterPackager;)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm_nativeSkipStep
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
 * Method:    nativeStepFinal
 * Signature: (JIIIILedu/ustc/nodb/PregelGPU/Algorithm/SSSPshm/shmManager/shmNamePackager/shmWriterPackager;)I
 */
JNIEXPORT jint JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm_nativeStepFinal
  (JNIEnv *, jobject, jlong, jint, jint, jint, jint, jobject);

/*
 * Class:     edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm
 * Method:    nativeEnvClose
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_PregelGPU_Algorithm_SSSPshm_GPUNativeShm_nativeEnvClose
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
