/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class edu_ustc_nodb_SSSP_GPUNative */

#ifndef _Included_edu_ustc_nodb_SSSP_GPUNative
#define _Included_edu_ustc_nodb_SSSP_GPUNative
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     edu_ustc_nodb_SSSP_GPUNative
 * Method:    GPUClientSSSP
 * Signature: (J[J[Z[DIII)Lscala/collection/mutable/ArrayBuffer;
 */
JNIEXPORT jobject JNICALL Java_edu_ustc_nodb_SSSP_GPUNative_GPUClientSSSP
  (JNIEnv *, jobject, jlong, jlongArray, jbooleanArray, jdoubleArray, jint, jint, jint);

/*
 * Class:     edu_ustc_nodb_SSSP_GPUNative
 * Method:    GPUServerShutdown
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_SSSP_GPUNative_GPUServerShutdown
  (JNIEnv *, jobject, jint);

/*
 * Class:     edu_ustc_nodb_SSSP_GPUNative
 * Method:    GPUServerInit
 * Signature: (J[J[J[DLjava/util/ArrayList;I)Z
 */
JNIEXPORT jboolean JNICALL Java_edu_ustc_nodb_SSSP_GPUNative_GPUServerInit
  (JNIEnv *, jobject, jlong, jlongArray, jlongArray, jdoubleArray, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
